const mongoose = require("mongoose");

const ipSchema = new mongoose.Schema({
  deviceId: {
    type: String,
    required: [true, "Device Id Required"],
  },
  interfaceName: {
    type: String,
  },
  ipv4Con: {
    type: String,
  },
  ipv4Address: {
    type: String,
  },
  subnet: {
    type: String,
  },
  generatedByUserId: {
    type: String,
    required: [true, "Generated by UserId Required"],
  },
});
module.exports = mongoose.model("Ip", ipSchema);
