const mongoose = require("mongoose");

const rIpSchema = new mongoose.Schema({
  deviceId: {
    type: String,
    required: [true, "Device Id Required"],
  },
  devicePort: {
    type: String,
    required: [true, "Device Port Required"],
  },
  interfaceName: {
    type: String,
  },
  ipAddress: {
    type: String,
  },
  subnetMask: {
    type: String,
  },
  generatedByUserId: {
    type: String,
    required: [true, "Generated by UserId Required"],
  },
});

module.exports = mongoose.model("RIp", rIpSchema);
