const mongoose = require("mongoose");

const staticRouteSchema = new mongoose.Schema({
  staticRouteId: {
    type: String,
    required: [true, "Static Route Id Required"],
    unique: true,
  },
  deviceId: {
    type: String,
    required: [true, "Device Id Required"],
  },
  destinationNetwork: {
    type: String,
  },
  subnet: {
    type: String,
  },
  gateway: {
    type: String,
  },
  disabled: {
    type: Boolean,
  },
  description: {
    type: String,
  },
  pfsenseId: {
    type: Number,
  },
  pfsenseDeleteId: {
    type: Number,
  },
  generatedByUserId: {
    type: String,
    required: [true, "Generated by UserId Required"],
  },
});

module.exports = mongoose.model("StaticRoute", staticRouteSchema);
