const mongoose = require("mongoose");

const tempstaticRouteSchema = new mongoose.Schema({
  staticRouteId: {
    type: String,
    required: [true, "Static Route Id Required"],
  },
  deviceId: {
    type: String,
    required: [true, "Device Id Required"],
  },
  destinationNetwork: {
    type: String,
  },
  subnet: {
    type: String,
  },
  gateway: {
    type: String,
  },
  disabled: {
    type: Boolean,
  },
  description: {
    type: String,
  },
  generatedByUserId: {
    type: String,
    required: [true, "Generated by UserId Required"],
  },
  version: {
    type: String,
    required: [true, "Version Required"],
  },
});

module.exports = mongoose.model("tempStaticRoute", tempstaticRouteSchema);
