const mongoose = require("mongoose");

const temprIpSchema = new mongoose.Schema({
  deviceId: {
    type: String,
    required: [true, "Device Id Required"],
  },
  devicePort: {
    type: String,
    required: [true, "Device Port Required"],
  },
  interfaceName: {
    type: String,
  },
  ipAddress: {
    type: String,
  },
  subnetMask: {
    type: String,
  },
  generatedByUserId: {
    type: String,
    required: [true, "Generated by UserId Required"],
  },
  version: {
    type: String,
    required: [true, "Version Required"],
  },
});

module.exports = mongoose.model("tempRIp", temprIpSchema);
