const mongoose = require("mongoose");

const tempvlansSchema = new mongoose.Schema({
  vlansId: {
    type: String,
    required: [true, "VLAN Id Required"],
  },
  deviceId: {
    type: String,
    required: [true, "Device Id Required"],
  },
  parentInterface: {
    type: String,
  },
  vlanTag: {
    type: String,
  },
  vlanPriority: {
    type: String,
  },
  description: {
    type: String,
  },
  generatedByUserId: {
    type: String,
    required: [true, "Generated by UserId Required"],
  },
  version: {
    type: String,
    required: [true, "Version Required"],
  },
});

module.exports = mongoose.model("tempVlans", tempvlansSchema);
