const mongoose = require("mongoose");

const tempipSchema = new mongoose.Schema({
  deviceId: {
    type: String,
    required: [true, "Device Id Required"],
  },
  interfaceName: {
    type: String,
  },
  ipv4Con: {
    type: String,
  },
  ipv4Address: {
    type: String,
  },
  subnet: {
    type: String,
  },
  generatedByUserId: {
    type: String,
    required: [true, "Generated by UserId Required"],
  },
  version: {
    type: String,
    required: [true, "Version Required"],
  },
});
module.exports = mongoose.model("tempIp", tempipSchema);
