const mongoose = require("mongoose");

const vlansSchema = new mongoose.Schema({
  vlansId: {
    type: String,
    required: [true, "VLAN Id Required"],
    unique: true,
  },
  deviceId: {
    type: String,
    required: [true, "Device Id Required"],
  },
  parentInterface: {
    type: String,
  },
  vlanTag: {
    type: String,
  },
  vlanPriority: {
    type: String,
  },
  description: {
    type: String,
  },
  pfsenseId: {
    type: Number,
  },
  pfsenseDeleteId: {
    type: Number,
  },
  generatedByUserId: {
    type: String,
    required: [true, "Generated by UserId Required"],
  },
});

module.exports = mongoose.model("Vlans", vlansSchema);
