import React, { useEffect, useState } from "react";
import "../../Styles/ViewRegDev.css";
import HomePage from "./HomePage";
import LogsSingleRow from "./LogsSingleRow";
import AxiosInstance from "../../Axios/AxiosInstance";

const Logs = () => {
  const [data, setData] = useState([]);
  useEffect(() => {
    AxiosInstance.get("/admin/logs")
      .then((res) => {
        if (res.data.success === true) {
          setData(res.data.logs);
        }
      })
      .catch((err) => {
        alert(err.response.data.message);
      });
  }, []);
  return (
    <>
      <HomePage />
      <div className="viewregdevbody">
        <div className="container-xl">
          <div className="utable-responsive">
            <div className="utable-wrapper">
              <div className="utable-title">
                <div className="row">
                  <div className="col-sm-8">
                    <h2 style={{ color: "#39ace7" }}>Logs</h2>
                  </div>
                </div>
              </div>
              <table className="table table-striped table-hover table-bordered">
                <thead>
                  <tr>
                    <th>Sr. #</th>
                    <th>Generated By User Id</th>
                    <th>Date & Time</th>
                    <th>Description</th>
                  </tr>
                </thead>
                <tbody>
                  {data.map((test, index) => {
                    return (
                      <LogsSingleRow
                        key={index + 1}
                        sr={index + 1}
                        uid={test.generatedByUserId}
                        dt={test.dateAndTime}
                        desc={test.description}
                      />
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Logs;
